### PR TITLE
Update: Introductory text

### PR DESCRIPTION
**Pull request by imwatsi**

### CODE REVIEW

**Comment by mktcode** [comment]
@imwatsi Thanks! I like your text very much. I'm just afraid it's a little bit too long. If I remember correclty @elear wanted to cut down even my version, although I think at least certain degree of detail would be reasonable. Maybe we can combine the the best of all versions. :)

**Comment by imwatsi** [comment]
An overlay would be a good idea. So there will be shorter descriptions and more details will appear in the overlay, maybe when a person taps/clicks?

I can write shorter versions of what I wrote too.

What do you think about a carousel?

**Comment by utopian-io** [comment]
I am in for a shorter text, but an overlay can work good as well!

**Comment by diegopucci** [comment]
I am in for a shorter text, but an overlay can work good as well!

**Comment by imwatsi** [comment]
I submitted a pull request with three FAQs just now and I realized that the text I had written here fits well within the answers, since it's descriptive and longer. I'll probably use most of what I wrote here in the FAQs and work with it a bit.

> I am in for a shorter text, but an overlay can work good as well!

I think I can do a short paragraph with two or three sentences for you, and we can see if it works :)

**Pull request closed without merging**
